const data = {
  tutorials: [
    {
      name: 'Beginner java tutorial ',
      slug: 'beginner-java-tutorial ',
      category: 'programming',
      image: '/image/programming1.jpg', //600px x 400px
      price: 50,
      rating: 4,
      numberReviews: 20,
      description: 'beginner java tutorial, easy to learn.',
    },
    {
      name: 'intermediate java tutorial ',
      slug: 'intermediate-java-tutorial ',
      category: 'programming',
      image: '/image/programming2.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'intermediate java tutorial, easy to learn.',
    },
    {
      name: 'C tutorial',
      slug: 'C-tutorial',
      category: 'programming',
      image: '/image/programming3.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'C tutorial, easy to learn.',
    },
    {
      name: 'C++ tutorial',
      slug: 'C++-tutorial',
      category: 'programming',
      image: '/image/programming4.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'C++ tutorial, easy to learn.',
    },
    {
      name: 'Data Base Tutorial',
      slug: 'data-base-tutorial',
      category: 'programming',
      image: '/image/programming5.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'Data Base Tutorial, easy to learn.',
    },
    {
      name: 'Calculus I',
      slug: 'beginner-calculus-I-tutorial',
      category: 'mathematics',
      image: '/image/math1.jpg',
      price: 50,
      rating: 4,
      numberReviews: 20,
      description: 'Beginner Calculus I Tutorial, easy to learn.',
    },
    {
      name: 'Calculus II',
      slug: 'calculus-II-tutorial',
      category: 'mathematics',
      image: '/image/math2.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'Calculus II Tutorial, easy to learn.',
    },
    {
      name: 'Linear Algebra',
      slug: 'linear-algebra-tutorial',
      category: 'mathematics',
      image: '/image/math3.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'Linear Algebra Tutorial, easy to learn.',
    },
    {
      name: 'Discrete Mathematics',
      slug: 'discrete-mathematics-tutorial',
      category: 'mathematics',
      image: '/image/math4.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'Discrete Mathematics Tutorial, easy to learn.',
    },
    {
      name: 'Probability and Statistics',
      slug: 'probability-and-statistics-tutorial',
      category: 'mathematics',
      image: '/image/math5.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'Probability and Statistics Tutorial, easy to learn.',
    },
    {
      name: 'Physics I',
      slug: 'physics-I-tutorial',
      category: 'physics',
      image: '/image/phys1.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'Physics I Tutorial, easy to learn.',
    },
    {
      name: 'Waves',
      slug: 'waves-tutorial',
      category: 'physics',
      image: '/image/phys2.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'Waves Tutorial, easy to learn.',
    },
    {
      name: 'Fluids',
      slug: 'fluids-tutorial',
      category: 'physics',
      image: '/image/phys3.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'Fluids Tutorial, easy to learn.',
    },
    {
      name: 'Heat and Mass',
      slug: 'heat-and-mass-tutorial',
      category: 'physics',
      image: '/image/phys4.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'Heat and Mass Tutorial, easy to learn.',
    },
    {
      name: 'Optics',
      slug: 'optics-tutorial',
      category: 'physics',
      image: '/image/phys5.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'Physics 1 Tutorial, easy to learn.',
    },
    {
      name: 'Anatomy',
      slug: 'anatomy-tutorial',
      category: 'medicine',
      image: '/image/med1.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'Anatomy Tutorial, easy to learn.',
    },
    {
      name: 'Stomatology',
      slug: 'stomatology-tutorial',
      category: 'medicine',
      image: '/image/med2.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'Stomatology Tutorial, easy to learn.',
    },
    {
      name: 'Radiology',
      slug: 'radiology-tutorial',
      category: 'medicine',
      image: '/image/med3.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'Radiology Tutorial, easy to learn.',
    },
    {
      name: 'Chirurgy',
      slug: 'chirurgy-tutorial',
      category: 'medicine',
      image: '/image/med4.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'Chirurgy Tutorial, easy to learn.',
    },
    {
      name: 'Court Medicine',
      slug: 'court-medicine-tutorial',
      category: 'medicine',
      image: '/image/med5.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'Court Medicine Tutorial, easy to learn.',
    },
    {
      name: 'Biology I',
      slug: 'biology-I-tutorial',
      category: 'science',
      image: '/image/sci1.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'Biology Tutorial, easy to learn.',
    },
    {
      name: 'Chemistry I',
      slug: 'chemistry-I-tutorial',
      category: 'science',
      image: '/image/sci2.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'Chemistry Tutorial, easy to learn.',
    },
    {
      name: 'MicrobiologyI',
      slug: 'microbiology-I-tutorial',
      category: 'science',
      image: '/image/sci3.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'Microbiology Tutorial, easy to learn.',
    },
    {
      name: 'Biochemistry',
      slug: 'biochemistry-I-tutorial',
      category: 'science',
      image: '/image/sci4.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'Biochemistry Tutorial, easy to learn.',
    },
    {
      name: 'Microchemistry',
      slug: 'microchemistry-I-tutorial',
      category: 'science',
      image: '/image/sci5.jpg',
      price: 70,
      rating: 4.5,
      numberReviews: 10,
      description: 'Microchemistry Tutorial, easy to learn.',
    },
  ],
};
export default data;
